# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9887b30cf15e402ccdc26815e8bb2bcc0ae5d06859624f47ae99dbb67334376acd3d6b8959951830ec98fc2ea4a68a07e826208f53e202c58914e1856cc1a9

test:
  secret_key_base: 3a35b0760d414df1e1dd8d7a295f0266ef8cf3b2d441e21986e62429c93a0ab719753a9aa5b0de9ff47cfeea626f598ee55a39ac4576f157ca583f22f28ba5c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
